---
name: HTML-Tree
version: 4.0
author:
  - 'Jeff Fearn <Jeff.Fearn@gmail.com>'
abstract: build and scan parse-trees of HTML
license: perl
resources:
  license: ~
requires:
  HTML::Parser: 3.46
  HTML::Tagset: 3.02
  perl: 5.8.0
build_requires:
  HTML::Parser: 3.46
  HTML::Tagset: 3.02
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
provides:
  HTML::AsSubs:
    file: lib/HTML/AsSubs.pm
    version: 1.16
  HTML::Element:
    file: lib/HTML/Element.pm
    version: 4.0
  HTML::Element::traverse:
    file: lib/HTML/Element/traverse.pm
    version: 0
  HTML::Parse:
    file: lib/HTML/Parse.pm
    version: 2.71
  HTML::Tree:
    file: lib/HTML/Tree.pm
    version: 4.0
  HTML::TreeBuilder:
    file: lib/HTML/TreeBuilder.pm
    version: 4.0
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
