--- #YAML:1.0
name:                HTML-Tree
version:             3.19_02
abstract:            build and scan parse-trees of HTML
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Sean M. Burke (sburke@cpan.org)
distribution_type:   module
requires:     
    HTML::Parser:                  2.19
    HTML::Tagset:                  3.02
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
